version: '3.3'

services:
  backend:
    build: ./backend
    ports:
      - '8000:8000'
    env_file:
      - .env
    healthcheck:
      test: curl --fail http://localhost:8000/ || exit 1
      timeout: 20s
      retries: 10

  frontend:
    build: ./frontend
    ports:
      - '8501:8501'
    depends_on:
      - backend

  nginx:
    container_name: nginx
    restart: always
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - frontend

volumes:
  assignemnt-04: